# Site settings
title: Eight Kids Farm
email: nkidsfarm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <b>Raising adults since 2000.</b><br>
  We're a family farm in Dexter, MI raising our 8 children to be amazing adults with the help of our sheep, cows, chickens, pigs, and bees.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nkidsfarm.com" # the base hostname & protocol for your site
twitter_username: nkidsfarm
facebook_username: nkidsfarm

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
